CREATE DATABASE IF NOT EXISTS alumnosDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE alumnosDB;

CREATE TABLE IF NOT EXISTS alumnos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL,
  apellido VARCHAR(60) NOT NULL,
  edad INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
